package com.github.sqrlserverjava.util;

/**
 * Utility class to extract build info generated by the net.mgorski.quicktag pom plugin. That plugin generates a source
 * file which is excluded from SCM, so we must use reflection to access it. Encapsulate that logic here
 * 
 * @author Dave Badia
 *
 */
public final class VersionExtractor {
	public enum Module {
		BASE("util"), ATMOSPHERE("atmosphere"), EXAMPLE_APP("example"),
		;

		private final String packagePath;

		private Module(String packagePath) {
			this.packagePath = packagePath;
		}
	};
	
	private VersionExtractor() {
		// util class
	}

	public static String extractDetailedBuildInfo(Module module) {
		// The Version class may not be present in eclipse, so use reflection so it doesn't fail the build or test cases
		try {
			Class<?> clazz = Class.forName("com.github.sqrlserverjava." + module.packagePath + ".Version");
			return (String) clazz.getField("BANNER_FULL").get(null);
		} catch (RuntimeException | ReflectiveOperationException e) {
			return "Could not extract build info for " + module + ": " + e.getMessage();
		}
	}

}
